export const LISTING_CATEGORIES = [
  "trending",
  "rooms",
  "iconic",
  "mountains",
  "castles",
  "pools",
  "camping",
  "farms",
  "arctic",
  "domes",
  "boats",
];

export const PROPERTY_TYPES = [
  "apartment",
  "house",
  "villa",
  "cottage",
  "cabin",
  "studio",
  "loft",
  "treehouse",
  "boat",
  "camper",
  "tent",
  "bungalow",
  "chalet",
  "castle",
  "farm",
  "other",
];

export const AMENITIES_LIST = [
  "wifi",
  "kitchen",
  "washer",
  "dryer",
  "air_conditioning",
  "heating",
  "dedicated_workspace",
  "iron",
  "hair_dryer",
  "hangers",
  "bed_linens",
  "extra_pillows_and_blankets",
  "room_darkening_shades",
  "hot_water",
  "shampoo",
  "body_soap",
  "towels",
  "smoke_alarm",
  "carbon_monoxide_alarm",
  "fire_extinguisher",
  "first_aid_kit",
  "tv",
  "cable_tv",
  "streaming_services",
  "books_and_reading_material",
  "pool",
  "hot_tub",
  "bbq_grill",
  "outdoor_dining",
  "fire_pit",
  "beach_access",
  "lake_access",
  "ski_in_ski_out",
  "mountain_view",
  "ocean_view",
  "garden",
  "patio",
  "balcony",
  "free_parking",
  "paid_parking",
  "ev_charger",
  "gym",
  "elevator",
  "crib",
  "high_chair",
  "children_books_and_toys",
  "children_dinnerware",
  "step_free_access",
  "wide_doorway",
  "accessible_parking",
  "breakfast",
  "cleaning_available",
  "luggage_dropoff",
  "long_term_stays_allowed",
  "pets_allowed",
  "smoking_allowed",
];

export const LISTING_STATUSES = ["active", "inactive", "suspended", "deleted"];

export const SEARCH_SORT_VALUES = [
  "createdAt",
  "price_asc",
  "price_desc",
  "rating",
  "popular",
];

export const USER_ROLES = ["user", "host", "admin"];
export const PROVIDERS = ["local", "google", "github"];
export const THEMES = ["light", "dark", "system"];
export const PROFILE_VISIBILITY = ["public", "private", "hosts_only"];
export const CURRENCIES = [
  "INR",
  "USD",
  "EUR",
  "GBP",
  "JPY",
  "AUD",
  "CAD",
  "SGD",
];
export const LANGUAGES = ["en", "hi", "es", "fr", "de", "ja", "zh", "ar"];
