"use strict";

const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    shortDescription:
      "Stunning ocean views with direct beach access — your perfect coastal escape.",
    description:
      "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy beach access.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    pricing: {
      nightlyPrice: 1500,
      cleaningFee: 120,
      serviceFee: 80,
      taxes: 150,
    },
    location: "Malibu",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
    category: "trending",
    propertyType: "cottage",
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    maxGuests: 4,
    amenities: [
      "wifi",
      "kitchen",
      "free_parking",
      "ocean_view",
      "beach_access",
      "bbq_grill",
      "hot_water",
    ],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      smokingAllowed: false,
      petsAllowed: true,
    },
    featured: true,
    status: "active",
    draft: false,
    minimumStay: 2,
    maximumStay: 30,
  },
  {
    title: "Modern Loft in Downtown",
    shortDescription:
      "Stylish city-centre loft with skyline views — perfect for urban explorers.",
    description:
      "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    pricing: {
      nightlyPrice: 1200,
      cleaningFee: 80,
      serviceFee: 60,
      taxes: 120,
    },
    location: "New York City",
    country: "United States",
    geometry: { type: "Point", coordinates: [-74.006, 40.7128] },
    category: "boats",
    propertyType: "loft",
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    maxGuests: 2,
    amenities: [
      "wifi",
      "kitchen",
      "air_conditioning",
      "heating",
      "dedicated_workspace",
      "elevator",
      "tv",
    ],
    houseRules: {
      checkInTime: "16:00",
      checkOutTime: "10:00",
      smokingAllowed: false,
      petsAllowed: false,
    },
    featured: false,
    status: "active",
    draft: false,
  },
  {
    title: "Mountain Retreat",
    shortDescription:
      "Unplug in this peaceful mountain cabin surrounded by pristine nature.",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    pricing: {
      nightlyPrice: 1000,
      cleaningFee: 90,
      serviceFee: 50,
      taxes: 100,
    },
    location: "Aspen",
    country: "United States",
    geometry: { type: "Point", coordinates: [-106.8175, 39.1911] },
    category: "mountains",
    propertyType: "cabin",
    bedrooms: 3,
    bathrooms: 2,
    beds: 4,
    maxGuests: 6,
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "free_parking",
      "mountain_view",
      "fire_pit",
      "bbq_grill",
      "hot_tub",
    ],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      petsAllowed: true,
      smokingAllowed: false,
    },
    featured: true,
    status: "active",
    draft: false,
    minimumStay: 3,
  },
  {
    title: "Historic Villa in Tuscany",
    shortDescription:
      "A beautifully restored villa amid rolling Tuscan hills and vineyards.",
    description:
      "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    pricing: {
      nightlyPrice: 2500,
      cleaningFee: 200,
      serviceFee: 150,
      taxes: 250,
    },
    location: "Florence",
    country: "Italy",
    geometry: { type: "Point", coordinates: [11.2558, 43.7696] },
    category: "castles",
    propertyType: "villa",
    bedrooms: 5,
    bathrooms: 4,
    beds: 6,
    maxGuests: 10,
    amenities: [
      "wifi",
      "kitchen",
      "pool",
      "garden",
      "free_parking",
      "bbq_grill",
      "outdoor_dining",
      "hot_water",
    ],
    houseRules: {
      checkInTime: "14:00",
      checkOutTime: "12:00",
      smokingAllowed: false,
      partiesAllowed: false,
    },
    featured: true,
    status: "active",
    draft: false,
    minimumStay: 5,
  },
  {
    title: "Secluded Treehouse Getaway",
    shortDescription:
      "Live among the treetops in this magical nature-lover's treehouse.",
    description:
      "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    pricing: { nightlyPrice: 800, cleaningFee: 60, serviceFee: 40, taxes: 80 },
    location: "Portland",
    country: "United States",
    geometry: { type: "Point", coordinates: [-122.6765, 45.5231] },
    category: "camping",
    propertyType: "treehouse",
    bedrooms: 1,
    bathrooms: 1,
    beds: 1,
    maxGuests: 2,
    amenities: ["wifi", "hot_water", "heating", "garden", "fire_pit"],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      smokingAllowed: false,
      petsAllowed: false,
    },
    featured: false,
    status: "active",
    draft: false,
  },
  {
    title: "Beachfront Paradise",
    shortDescription:
      "Step out onto the sand from this stunning Cancun beachfront condo.",
    description:
      "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    pricing: {
      nightlyPrice: 2000,
      cleaningFee: 150,
      serviceFee: 100,
      taxes: 200,
    },
    location: "Cancun",
    country: "Mexico",
    geometry: { type: "Point", coordinates: [-86.8515, 21.1619] },
    category: "pools",
    propertyType: "apartment",
    bedrooms: 2,
    bathrooms: 2,
    beds: 3,
    maxGuests: 5,
    amenities: [
      "wifi",
      "kitchen",
      "pool",
      "air_conditioning",
      "beach_access",
      "ocean_view",
      "free_parking",
    ],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      smokingAllowed: false,
      petsAllowed: false,
    },
    featured: false,
    status: "active",
    draft: false,
  },
  {
    title: "Rustic Cabin by the Lake",
    shortDescription:
      "Fish, kayak, and unwind at this cosy lakeside cabin in Tahoe.",
    description:
      "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    pricing: { nightlyPrice: 900, cleaningFee: 75, serviceFee: 45, taxes: 90 },
    location: "Lake Tahoe",
    country: "United States",
    geometry: { type: "Point", coordinates: [-120.0324, 39.0968] },
    category: "camping",
    propertyType: "cabin",
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    maxGuests: 4,
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "free_parking",
      "lake_access",
      "bbq_grill",
      "fire_pit",
      "smoke_alarm",
    ],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      petsAllowed: true,
      smokingAllowed: false,
    },
    featured: false,
    status: "active",
    draft: false,
    minimumStay: 2,
  },
  {
    title: "Luxury Penthouse with City Views",
    shortDescription: "Panoramic city views from a world-class LA penthouse.",
    description:
      "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    pricing: {
      nightlyPrice: 3500,
      cleaningFee: 300,
      serviceFee: 200,
      taxes: 350,
    },
    location: "Los Angeles",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.2437, 34.0522] },
    category: "iconic",
    propertyType: "apartment",
    bedrooms: 3,
    bathrooms: 3,
    beds: 4,
    maxGuests: 6,
    amenities: [
      "wifi",
      "kitchen",
      "pool",
      "gym",
      "air_conditioning",
      "heating",
      "elevator",
      "dedicated_workspace",
      "tv",
      "streaming_services",
    ],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      smokingAllowed: false,
      partiesAllowed: false,
    },
    featured: true,
    status: "active",
    draft: false,
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    shortDescription: "Hit the Swiss Alps slopes directly from your doorstep.",
    description:
      "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    pricing: {
      nightlyPrice: 3000,
      cleaningFee: 250,
      serviceFee: 180,
      taxes: 300,
    },
    location: "Verbier",
    country: "Switzerland",
    geometry: { type: "Point", coordinates: [7.2286, 46.0961] },
    category: "arctic",
    propertyType: "chalet",
    bedrooms: 4,
    bathrooms: 3,
    beds: 5,
    maxGuests: 8,
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "ski_in_ski_out",
      "hot_tub",
      "mountain_view",
      "free_parking",
      "fire_pit",
    ],
    houseRules: {
      checkInTime: "16:00",
      checkOutTime: "10:00",
      smokingAllowed: false,
    },
    featured: true,
    status: "active",
    draft: false,
    minimumStay: 7,
  },
  {
    title: "Safari Lodge in the Serengeti",
    shortDescription:
      "Witness the Great Migration from your private luxury lodge.",
    description:
      "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    pricing: {
      nightlyPrice: 4000,
      cleaningFee: 350,
      serviceFee: 200,
      taxes: 400,
    },
    location: "Serengeti National Park",
    country: "Tanzania",
    geometry: { type: "Point", coordinates: [34.8333, -2.3333] },
    category: "camping",
    propertyType: "other",
    bedrooms: 2,
    bathrooms: 2,
    beds: 2,
    maxGuests: 4,
    amenities: ["hot_water", "breakfast", "first_aid_kit", "smoke_alarm"],
    houseRules: {
      checkInTime: "14:00",
      checkOutTime: "10:00",
      smokingAllowed: false,
    },
    featured: true,
    status: "active",
    draft: false,
    minimumStay: 3,
  },
  {
    title: "Historic Canal House",
    shortDescription:
      "Preserved 17th-century canal house in Amsterdam's iconic district.",
    description:
      "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    pricing: {
      nightlyPrice: 1800,
      cleaningFee: 140,
      serviceFee: 90,
      taxes: 180,
    },
    location: "Amsterdam",
    country: "Netherlands",
    geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
    category: "iconic",
    propertyType: "house",
    bedrooms: 3,
    bathrooms: 2,
    beds: 3,
    maxGuests: 5,
    amenities: ["wifi", "kitchen", "heating", "washer", "tv", "hot_water"],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "11:00",
      smokingAllowed: false,
      partiesAllowed: false,
    },
    featured: false,
    status: "active",
    draft: false,
  },
  {
    title: "Private Island Retreat",
    shortDescription:
      "The ultimate exclusive escape — an entire island to yourself.",
    description:
      "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    pricing: {
      nightlyPrice: 10000,
      cleaningFee: 1000,
      serviceFee: 500,
      taxes: 1000,
    },
    location: "Fiji",
    country: "Fiji",
    geometry: { type: "Point", coordinates: [178.065, -17.7134] },
    category: "pools",
    propertyType: "villa",
    bedrooms: 6,
    bathrooms: 6,
    beds: 8,
    maxGuests: 12,
    amenities: [
      "wifi",
      "kitchen",
      "pool",
      "beach_access",
      "ocean_view",
      "bbq_grill",
      "hot_tub",
      "kayaks",
      "breakfast",
      "smoke_alarm",
    ],
    houseRules: {
      checkInTime: "14:00",
      checkOutTime: "12:00",
      smokingAllowed: false,
    },
    featured: true,
    status: "active",
    draft: false,
    minimumStay: 5,
  },
  {
    title: "Charming Cottage in the Cotswolds",
    shortDescription:
      "A thatched-roof dream cottage in England's most picturesque region.",
    description:
      "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    pricing: {
      nightlyPrice: 1200,
      cleaningFee: 90,
      serviceFee: 60,
      taxes: 120,
    },
    location: "Cotswolds",
    country: "United Kingdom",
    geometry: { type: "Point", coordinates: [-1.7841, 51.9294] },
    category: "farms",
    propertyType: "cottage",
    bedrooms: 2,
    bathrooms: 1,
    beds: 2,
    maxGuests: 4,
    amenities: [
      "wifi",
      "kitchen",
      "heating",
      "garden",
      "fire_pit",
      "washer",
      "hot_water",
    ],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "10:00",
      petsAllowed: true,
      smokingAllowed: false,
    },
    featured: false,
    status: "active",
    draft: false,
  },
  {
    title: "Beachfront Bungalow in Bali",
    shortDescription:
      "Private pool bungalow steps from Bali's legendary sandy shores.",
    description:
      "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    pricing: {
      nightlyPrice: 1800,
      cleaningFee: 140,
      serviceFee: 90,
      taxes: 180,
    },
    location: "Bali",
    country: "Indonesia",
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
    category: "pools",
    propertyType: "bungalow",
    bedrooms: 2,
    bathrooms: 2,
    beds: 2,
    maxGuests: 4,
    amenities: [
      "wifi",
      "kitchen",
      "pool",
      "air_conditioning",
      "beach_access",
      "ocean_view",
      "breakfast",
      "hot_water",
    ],
    houseRules: {
      checkInTime: "14:00",
      checkOutTime: "11:00",
      smokingAllowed: false,
    },
    featured: false,
    status: "active",
    draft: false,
    minimumStay: 3,
  },
  {
    title: "Desert Oasis in Dubai",
    shortDescription:
      "Opulent desert villa with a private infinity pool in the heart of Dubai.",
    description:
      "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    pricing: {
      nightlyPrice: 5000,
      cleaningFee: 450,
      serviceFee: 250,
      taxes: 500,
    },
    location: "Dubai",
    country: "United Arab Emirates",
    geometry: { type: "Point", coordinates: [55.2708, 25.2048] },
    category: "domes",
    propertyType: "villa",
    bedrooms: 4,
    bathrooms: 4,
    beds: 5,
    maxGuests: 8,
    amenities: [
      "wifi",
      "kitchen",
      "pool",
      "air_conditioning",
      "gym",
      "dedicated_workspace",
      "tv",
      "free_parking",
      "breakfast",
    ],
    houseRules: {
      checkInTime: "15:00",
      checkOutTime: "12:00",
      smokingAllowed: false,
      partiesAllowed: false,
    },
    featured: true,
    status: "active",
    draft: false,
  },
];

module.exports = { data: sampleListings };
