export const SEED_PASSWORD = "Wanderlust@2025";

export const hosts = [
  {
    username: "coastalhost",
    email: "maria.host@wanderlust.com",
    firstName: "Maria",
    lastName: "Alvarez",
    bio: "Hosting beachfront and coastal escapes for 6 years. I love helping guests find their perfect ocean view.",
    role: "host",
  },
  {
    username: "mountainhost",
    email: "jake.host@wanderlust.com",
    firstName: "Jake",
    lastName: "Connor",
    bio: "Mountain cabin specialist based out of Aspen. Ask me about the best local hiking trails!",
    role: "host",
  },
  {
    username: "urbanhost",
    email: "priya.host@wanderlust.com",
    firstName: "Priya",
    lastName: "Sharma",
    bio: "City-living enthusiast hosting modern apartments in the world's most exciting downtowns.",
    role: "host",
  },
  {
    username: "luxuryhost",
    email: "elliot.host@wanderlust.com",
    firstName: "Elliot",
    lastName: "Whitmore",
    bio: "Curating ultra-premium villas, penthouses, and private retreats for discerning travelers.",
    role: "host",
  },
  {
    username: "heritagehost",
    email: "sofia.host@wanderlust.com",
    firstName: "Sofia",
    lastName: "Marchetti",
    bio: "Restoring and sharing historic homes across Europe — every stay comes with a story.",
    role: "host",
  },
  {
    username: "adventurehost",
    email: "noah.host@wanderlust.com",
    firstName: "Noah",
    lastName: "Bennett",
    bio: "Glamping domes, treehouses, and houseboats — for travelers who want something different.",
    role: "host",
  },
];

export const travelers = [
  {
    username: "wanderingjess",
    email: "jess.traveler@example.com",
    firstName: "Jessica",
    lastName: "Nguyen",
    bio: "Weekend-trip addict. Always chasing good coffee and better views.",
    role: "user",
  },
  {
    username: "globetrotter_sam",
    email: "sam.traveler@example.com",
    firstName: "Samuel",
    lastName: "Okafor",
    bio: "32 countries and counting. I review everything in painful detail.",
    role: "user",
  },
  {
    username: "familyfirst_dana",
    email: "dana.traveler@example.com",
    firstName: "Dana",
    lastName: "Kowalski",
    bio: "Traveling with two kids under 8 — I know what actually makes a place family-friendly.",
    role: "user",
  },
  {
    username: "remote_raj",
    email: "raj.traveler@example.com",
    firstName: "Raj",
    lastName: "Mehta",
    bio: "Remote software engineer. Wi-Fi speed makes or breaks my stay.",
    role: "user",
  },
  {
    username: "honeymoon_liv",
    email: "olivia.traveler@example.com",
    firstName: "Olivia",
    lastName: "Bennett",
    bio: "Planning the perfect honeymoon trip, one stunning listing at a time.",
    role: "user",
  },
  {
    username: "budget_backpacker",
    email: "ty.traveler@example.com",
    firstName: "Tyler",
    lastName: "Brooks",
    bio: "Backpacking on a shoestring. Looking for clean, safe, and cheap.",
    role: "user",
  },
  {
    username: "petfriendly_amy",
    email: "amy.traveler@example.com",
    firstName: "Amy",
    lastName: "Fitzgerald",
    bio: "Never travel without my golden retriever, Biscuit. Pet-friendly or it's a no.",
    role: "user",
  },
  {
    username: "solo_explorer_kim",
    email: "kim.traveler@example.com",
    firstName: "Kimberly",
    lastName: "Park",
    bio: "Solo female traveler. Safety and a good neighborhood matter most to me.",
    role: "user",
  },
];
